package my.app.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import my.app.domain.PublicResource;


@Repository
public interface PublicResourceRepository extends JpaRepository<PublicResource, Long> {
  List<PublicResource> findAllByName(String name);

  // the implementation of this interface will be generated by Spring
  // JpaRepository defines some base methods: findAll, getOne, delete, etc.)
}
